//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_BTL_NguyenDuyHung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int maTraLoi { get; set; }
        public Nullable<int> maCauHoi { get; set; }
        public Nullable<int> maTaiKhoan { get; set; }
        public string traLoi { get; set; }
        public Nullable<bool> kiemTra { get; set; }
    
        public virtual question question { get; set; }
        public virtual user user { get; set; }
    }
}
