//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_BTL_NguyenDuyHung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int maBaiHoc { get; set; }
        public Nullable<int> maKhoaHoc { get; set; }
        public string tieuDe { get; set; }
        public string noiDung { get; set; }
        public Nullable<int> thuTu { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
